export const TICKER_LIST = Array.from(new Set([
  "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "BRK.B", "V", "UNH",
  "JNJ", "WMT", "XOM", "MA", "PG", "AVGO", "HD", "ORCL", "CVX", "LLY",
  "COST", "MRK", "ABBV", "KO", "PEP", "BAC", "ADBE", "CSCO", "CRM", "TMO",
  "MCD", "ACN", "ABT", "LIN", "WFC", "DHR", "INTC", "DIS", "PM", "AMD",
  "TXN", "MS", "RTX", "VZ", "HON", "NEE", "INTU", "LOW", "PFE", "AMAT",
  "AXP", "UNP", "IBM", "CAT", "SYK", "GE", "SPGI", "GS", "ISRG", "ELV",
  "GILD", "DE", "LMT", "PLD", "BLK", "NOW", "TJX", "ADP", "MMC", "ADI",
  "AMGN", "MDLZ", "C", "AMT", "T", "CB", "REGN", "BA", "LRCX", "CI",
  "MU", "VRTX", "ZTS", "BSX", "MO", "SLB", "ETN", "BDX", "PANW", "SBUX",
  "FI", "PYPL", "CVS", "KLAC", "SNPS", "BKNG", "HUM", "CDNS", "WM",
  "MCO", "EOG", "AON", "TGT", "CMCSA", "CL", "ITW", "SHW", "MAR", "EMR",
  "FDX", "PH", "APH", "USB", "GD", "ROP", "PGR", "ECL", "MSI", "MDT",
  "MPC", "MCK", "D", "NSC", "ORLY", "CTAS", "MNST", "ADM", "AIG", "WELL",
  "PXD", "O", "CCI", "AZO", "KDP", "DXCM", "BKR", "FTNT", "VICI", "ERE",
  "IDXX", "KMB", "DLR", "IQV", "A", "OKE", "AJG", "MET", "DDU", "CNC",
  "TRV", "PCAR", "PSA", "OXY", "COR", "CMI", "DFS", "STZ", "GIS", "COF",
  "NEM", "AEP", "RMD", "TEL", "CPRT", "SYY", "STT", "HCA",
  "EW", "DOW", "PRU", "GWW", "HLT", "BIIB", "OTIS", "ALL", "EXC", "PAYX",
  "VLO", "AME", "KR", "K", "DHI", "CTSH", "WMB", "ROST", "SPG", "CDW",
  "YUM", "EA", "MTD", "EXPE", "LEN", "WST", "ENPH", "ANSS", "ODFL",
  "MPWR", "ON", "FAST", "AVB", "CPT", "DRE", "IRM", "INVH", "MAA",
  "UDR", "VTR", "PEAK", "ARE", "BXP", "HST", "REG", "FRT", "KIM", "WY",
  "SBAC", "CSGP", "EQIX", "VRSN", "KEYS", "TT", "CARR", "IR",
  "TRGP", "CTRA", "COP", "HAL", "HES", "DVN",
  "FANG", "APA", "MRO", "KMI", "BTC", "ETH", "SOL", "ADA", "XRP", "DOT", "LINK", "AVAX", "MATIC", "LTC",
  "PLTR", "SOFI", "COIN", "DKNG", "HOOD", "AFRM", "UPST", "SHOP", "SQ", "U", "RBLX", "PATH", "SNOW", "Z", "OKTA",
  "MONG", "DDOG", "ZS", "CRWD", "NET", "TEAM", "MDB", "DOCU", "TWLO", "SPLK", "FSLY", "PINS", "SNAP", "DASH", "ABNB",
  "UBER", "LYFT", "ROKU", "SPOT", "NFLX", "BYND", "CVNA", "CHPT", "QS", "RIVN", "LCID", "NKLA", "F", "GM", "TM",
  "HMC", "VWAGY", "BMWYY", "TSM", "ASML", "NXP", "STM", "INFY", "WIT", "SAP", "ASAN", "SMCI", "ARM", "AVGO", "ANET"
])).sort();
